= 面试

其实早有跳槽的打算了，所以趁着金三银四，开始投简历约面试。

在拉勾网和 Boss 直聘上投了一个星期的运维相关岗位，从 18k 一直投到了 5k，结果一
份面试邀请都没有收到。在这个过程中我发现各个公司运维岗位的工作内容差异很大，有
的需要驻场，有的需要轮班，有的是机房管理，有的是电脑维修，等等。总的看了一圈下
来，大多数运维岗位的要求只需要会常用软件的安装和配置，以及服务器的监控和排错，
很少有需要有开发相关的技能。因此我最后决定还是把方向放到 Python 后台开发或者
DevOps 相关的岗位上。

从 3 月 7 号开始陆续接到了公司的面试，以下就对这几场面试做一次记录。

== 互道科技

3 月 7 号

之前约的下午一点半到公司，面试当天我提前到了，被安排在会议室里面等候。因为第一
次面试，所以心里还是有点紧张，不过在会议室等待的过程中，心态也渐渐调整过来了。

首先是 HR ，先让我先大致介绍自己的情况，因为第一次面试，之前对自我介绍这一块也
没有太多的构思，所以讲着讲着就有些跑偏了，能明显感觉到 HR 对我跑题的内容有些不
感冒，还好 HR 主动发问，把我又拉回了正题。之后又聊了我的相关工作经历，HR 在最后
也主动向我介绍了公司的业务与发展，一顿巴拉巴拉，让我感觉还挺 NB，呵呵。

之后 HR 抱来一台苹果笔记本，让我在 20 分钟之内完成一道题目，可以使用搜索引擎。
然后 HR 就把我独自留在了会议室里面做题。

题目大概是这样子的：有一份 xlsx 文件，每行中有三个单元格，这三个单元格分别对应
数据库中的 a, b, c 字段，这份文件中有 10 万行，要求把这些数据拼成一条 SQL
INSERT 语句，插入到数据库中。

仔细读了两遍题目，这题的核心应该是考验对内存的有效利用。所以思路应该使用 Python
的 generator 来拼出该 SQL 语句以节省内存的使用。但我想这还不够，在读取 xlsx 的
时候，如果是一次性把文件都加载进来，也会消耗不少的内存空间，所以应该用到 buffer
来流式读取 xlsx 文件。

有了思路就很好办了，但我对 Python 读取 xlsx 的相关库都不太熟悉，而且也不知道它
们是否有 buffer 这个功能，于是就构造了一个 xlsx_open 函数，并把我的大致思路写了
下来（我觉得其实面试题能写个思路就够了，没必要非得运行成功）。

这里面还有一个小插曲，在做完题等待技术官的时候，我好奇用 find 命令全盘找了一下
这道题的同名文件，结果还真发现了两份，文件日期是去年九月份。我打开一看是同一道
题目，顺便粗略看了一下他们的答案，呵呵。

等技术官进来，我和他讲了我的解题思路，能看得出来，面试官对我的解法还是挺满意的
。之后又聊起了我的工作的项目。在聊的过程中，能明显发现，技术官的重点一直在业务
上面。我又见缝插针地和面试官聊起了我的个人项目，面试官对我的评价也很高，觉得我
和其他人不一样，在于我对编程的热爱。


3 月 8 号

这天发生了一个很巧的事情，中午大概一点的时候，我去全家买东西，正好碰到了昨天面
试的技术官，于是趁他吃饭的功夫，又和他聊了一番，得到的情况是公司主要是做 ERP 系
统的，使用 Python 的 OpenERP 框架，没有单元测试，这个技术官负责一个 3 到 4 人的
团队。

3 月 12 号

这天是二面，面试我的是公司的一个项目主管。问了很多数据库相关的内容，虽然我这块
不是很熟，但也把我个人的理解都讲了出来。另外还有一道算法题，回答的也还行。因为
之前有了解到公司内部有一个基础架构团队，所以聊的过程中，我透露出我不太喜欢写业
务，而是偏向系统，底层，运维多一些，当然面试官并没有做出正面的回答。

3 月 15 号

收到 HR 的邮件回复，未能录用，主要原因在于我表达的个人发展方向和公司的用人要求
有较大出入，多维度评估之后认为不适合。

