#!/bin/bash

CRT_DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})")
SRC_DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})/src")
DST_DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})/docs")

msg() {
  echo "D. $@"
}

clean() {
  local src=$1
  local dst=$2
  local src_ext=$3
  local dst_ext=$4

  OLD_IFS=$IFS
  IFS=$'\n'

  for dir in $(find "$dst" -type d  -printf '%P\n'); do
    s=$src/$dir
    d=$dst/$dir

    if [[ ! -d $s ]]; then
      msg "$d"
      rm -rf "$d"
      continue
    fi
  done

  for file in $(find "$dst" -type f -printf '%P\n'); do
    s=$src/${file/%${dst_ext}/${src_ext}}
    d=$dst/$file

    if [[ ! -f $s ]]; then
      msg "$d"
      rm "$d"
      continue
    fi
  done

  IFS=$OLD_IFS
}

clean_blog() {
  local src dst
  for dir in $(find "$DST_DIR" -maxdepth 1 -type d -name '20[0-9][0-9]' -printf '%P\n'); do
    src=$SRC_DIR/$dir
    dst=$DST_DIR/$dir
    clean "$src" "$dst" rst html
  done
}

clean_notes() {
  local src=$SRC_DIR/notes
  local dst=$DST_DIR/notes
  clean "$src" "$dst" rst html
}

clean_code() {
  local src=graphviz
  local dst=code
  clean "$src" "$dst" dot jpg
}


# Main
clean_blog
clean_notes
#clean_code
