#!/usr/bin/env bash


DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})")

msg() {
  echo "D. " "$@"
}

comm_dir() {
  # Neet to set $regex and $adoc before run this function
  OLD_IFS=$IFS
  IFS=$'\n'

  for subdir in $(find -type d -regex "$regex"); do
    adoc_subdir=$adoc/$subdir

    if [[ ! -d $subdir ]]; then
      continue
    fi

    if [[ ! -d $adoc_subdir ]]; then
      msg "$subdir"
      rm -rf "$subdir"
      continue
    fi

    # File not suffixed with '.html'
    for dedication in $(find "$subdir" -maxdepth 1 -type f); do
        if [[ ! $dedication =~ .html$ ]]; then
          msg "$dedication"
          rm -rf "$dedication"
        fi
    done

    for dedication in $(comm -23 \
        <(ls "$subdir" | sed -E 's@(.*)\.html@\1@' | sort) \
        <(ls "$adoc_subdir" | sed -E 's@(.*)\.adoc@\1@') | sort); do
      # $dedication may be file or directory.
      if [[ -f $subdir/$dedication.html ]]; then
        dedication=$dedication.html
      fi
      msg "$subdir/$dedication"
      rm -rf "$subdir/$dedication"
    done
  done

  IFS=$OLD_IFS
}

comm_blog_dir() {
  adoc=$DIR/asciidoc/blog
  regex="^./20[0-9][0-9].*"
  comm_dir
}

comm_notes_dir() {
  adoc=$DIR/asciidoc
  regex="^./notes.*"
  comm_dir
}


# Ensure in this script directory
cd "$DIR"
comm_blog_dir
comm_notes_dir

