#!/usr/bin/env bash


DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})")

msg() {
  echo "D. " "$@"
}

comm_dir() {
  # Neet to set $regex and $rst before run this function
  OLD_IFS=$IFS
  IFS=$'\n'

  for subdir in $(find -type d -regex "$regex"  -printf '%P\n'); do
    
    # Skip `note/ns` directory
    if grep -Eq "^notes/ns" <(echo "$subdir"); then
      msg "$DIR/$subdir"
      rm -rf "$DIR/$subdir"
      continue
    fi

    rst_subdir=$rst/$subdir

    # Ensure $subdir is a directory
    if [[ ! -d $subdir ]]; then
      continue
    fi

    # Ensure $rst_subdir is a directory
    if [[ ! -d $rst_subdir ]]; then
      msg "$subdir"
      rm -rf "$subdir"
      continue
    fi

    # Then compare files in $subdir and $rst_subdir

    # Delete files which are not suffixed with '.html' first
    for dedication in $(find "$subdir" -maxdepth 1 -type f); do
        if [[ ! $dedication =~ .html$ ]]; then
          msg "$dedication"
          rm -rf "$dedication"
        fi
    done

    for dedication in $(comm -23 \
        <(ls "$subdir" | sed -E 's@(.*)\.html@\1@' | sort) \
        <(ls "$rst_subdir" | sed -E 's@(.*)\.rst@\1@') | sort); do
      # $dedication may be file or directory.
      if [[ -f $subdir/$dedication.html ]]; then
        dedication=$dedication.html
      fi
      msg "$subdir/$dedication"
      rm -rf "$subdir/$dedication"
    done
  done

  IFS=$OLD_IFS
}

comm_blog_dir() {
  rst=$DIR/reStructuredText
  regex="^./20[0-9][0-9].*"
  comm_dir
}

comm_notes_dir() {
  rst=$DIR/reStructuredText
  regex="^./notes.*"
  comm_dir
}


# Ensure we are in this script directory
cd "$DIR"
comm_blog_dir
comm_notes_dir

