#!/usr/bin/env bash

python_version=$(python -c "import sys; print(sys.version_info[0])")

firefox 127.0.0.1:8000/blog.html

if (( $python_version == 3 )); then
  python -m http.server 8000
elif (( $python_version == 2 )); then
  python -m SimpleHTTPServer 8000
else
  echo Unknown version of python
  exit 1
fi

