= OnePlus 5T 入手

上周末刷咸鱼的时候发现了了这款 OnePlus 5T 手机（标价 1550，配置 6G RAM + 64G
ROM)。卖家也是个搞机玩家，手机已经刷了 TWRP 和 DK ROM （基于官方 H2OS 改的ROM，
可以在 OnePlus 5T 中文论坛找到）。比较有趣的是，我在和卖家沟通时顺便探讨了一下
刷机经验，发现卖家常年混迹 OnePlus 5T 中文论坛，熟用论坛里“大神”自制的刷机工具
，却浑然分不清线刷和卡刷的区别。

和卖家沟通许久之后，决定入手这款手机。不过当时拍下这款手机之后还是有些顾虑，一
是手机已经刷过机（但了解之后发现以刷回官方 recovery 和 ROM），二是手机续航问题
，毕竟已经用过大半年，而且卖家是东北的（电池在低温环境下更容易损耗）。

所以怀着一颗期待而又有些小小担忧的心，今天终于拿到了手机（顺丰隔日达，用了三天
的时间，差评 :(）。开机之后简单体验了一下卖家刷的 DK ROM，并测试了手机的续航，
发现不开任何软件，亮屏消耗 1% 的电大概需要 15 分钟时间。之后就打算开始刷机了，
首先下载最新的 OxygenOS 5.1.7 ROM，然后通过卖家已经刷好的 TWRP，将其刷入手机，
可是等刷完重启之后发现一直重复进入 TWRP 界面，进去不系统，非常纳闷。于是我又找
了 OxygenOS 4.7.6 版本的 ROM，按照同样的方法再刷了一次，这次终于可以进系统了，
而且 recovery 也自动刷回了官方版本（我本来还想着需要手动刷一下官方 recovery），
但是我想要的是最新版的 OxygenOS，于是我又通过官方 recovery 刷入了之前下载的最新
版的 OxygenOS 5.1.7 ROM 。这样终于将手机系统还原成了官方版本。

之后，在新系统下测试了手机的续航：以消耗 1％ 的电量为准，不开任何软件，亮屏可以
维持 20 分钟的时间，打开 wifi，亮屏可以维持 10 分钟的时间，打开 wifi 看 YouTube
可以维持 5 分钟的时间（不过后来发现这样的测试方法不是特别严谨，因为首先要保证屏
幕的亮度是一致的，后来发现了一个名为
https://accubattery.zendesk.com/hc/en-us/articles/210224685-Getting-started-guide[[AccuBattery]
的软件，可以对手机电池以及耗电做一个全面的检测）。总之这样的结果还是较为满意的
。

之所以在当下 OnePlus 6T 都已经面世好久，却去购买上一代产品 5T 的原因。首先手机
行业早已进入性能过剩的年代，OnePlus 5T 对我来说完全够用。再者，考虑到明年开始进
入 5G 时代，而今年出的手机都没有 5G 模块，所以以后升级 5G 网络还得再换手机，这
样算下来不是很划得来。其次是刷机的因素， OnePlus 6T 采用了 Google 最新的 A／B
partition 结构，这样方便 OTA 升级，但是增加了刷机的难度。最后二手的价格非常甜。
综上种种原因，我选择 OnePlus 5T，这款对搞机用户友好，外观漂亮，性能优秀的手机（
我为 5T 代言，呵呵）。

看过之前文章的朋友应该知道，我在这之前还入手了一款 Essential Phone PH-1 手机，
所以这款 OnePlus 5T 是打算给家人用的。当然在这之前我还会继续使用一阵。

Thanks for reading :)
