= man

----
    man [options] [section] page ...
----

`man` will search for the desired manual pages within the index database
caches. A `section`, if provided, will direct man to look only in that section
of the manual. The default action is to search in all of the available sections
following a pre-defined order ("1 n l  8  3  2  3posix  3pm 3perl  3am 5 4 9 6
7" by default).

-   `-f`: Equivalent to whatis. Display a short description from the manual
    page, if available.

-   `-k`: Equivalent to apropos. Search the short manual page descriptions for
    keywords and display any matches.

-   `-K`: Search for text in all manual pages. This is a brute-force search,
    and is likely to take some time; if you can, you should specify a section
    to reduce the number of pages that need to be searched.

-   `-w`: Don't actually display the manual pages, but do print the location(s)
    of the source nroff files that would be formatted.

-   `-a`: By default, man will exit after displaying the most suitable manual
    page it finds. Using this option forces man to display all the manual pages
    with names that match the search criteria.

-   `--regex`: Show all pages with any part of either their names or their
    descriptions matching each page argument as a regular expression, as with
    apropos(1).

-   `--wildcard`: Show  all pages with any part of either their names or their
    descriptions matching each page argument using shell-style wildcards, as
    with apropos(1) --wildcard.

-   `--names-only`: If the --regex or --wildcard option is used, match only
    page names, not page descriptions. Otherwise, no effect.

== mandb

`mandb` will create or update the manual page index cache.

== manpath

The manpath configuration file `/etc/manpath.config` is used by the manual page
utilities to assess users' manpaths at run time, to indicate which manual page
hierarchies (manpaths) are to be treated as system hierarchies and to assign
them directories to be used for storing cat files.

If the environment variable `$MANPATH` is already set, the information contained
within `/etc/manpath.config` will not override it.

*Note*: If path directory not in the manpath configuration file but is one of
the elements in environment variable `PATH`, and if any of the `../man`, `man`,
`../share/man` or `share/man` subdirectories exists, they will be added to
manpath.  (use `catman -d` to check it)

== whatis

----
    whatis [options] name ...
----

`whatis` display one-line manual page descriptions.

Each manual page has a short description available within it. `whatis` searches
the manual page names and displays the manual page descriptions of any name
matched.  

-   `-r`: Interpret  each  name  as a regular expression.

-   `-w`: Interpret each name as a pattern containing shell style wildcards.

== apropos

----
    apropos [options] keyword ...
----

`apropos` search the manual page names and descriptions.

Each manual page has a short description available within it. `apropos`
searches the descriptions for instances of keyword.

-   `-r`: Interpret each keyword as a regular expression. This is the default
    behaviour. Each keyword will be matched against the page names and the
    descriptions independently.

-   `-w`: Interpret each keyword as a pattern containing shell style wildcards.
    Each keyword will be matched against the page names and the descriptions
    independently.

-   `-e`: Each keyword will be exactly matched against the page names and the
    descriptions.

-   `-a`: Only display items that match all the supplied keywords. The default
    is to display items that match any keyword.

== References

-   https://unix.stackexchange.com/a/63583
