= Bash Word Splitting

The shell scans the results of parameter expansion, command substitution, and
aritmetic expansion that did not occur within double quotes for word splitting.

The shell treats each character of _IFS_ as a delimiter, and splits the results
of the other expansions into words using these characters as field terminators.

If _IFS_ is unset, or its value is exactly <space><tab><newline>, the default,
then sequences of <space>, <tab>, and <newline> at the beginning and end of the
results of the previous expansions are ignored, and any sequence of _IFS_
characters not at the beginning or end serves to delimit words.

If _IFS_ has a value other than the default, then sequences of the whitespace
chacters <space>, <tab> and <newline> are ignored at the beginning and end of
the word, as long as the whitespace character is in the value of _IFS_ (an
_IFS_ whitespace characer). Any character in _IFS_ that is not _IFS_
whitespace, along with any adjacent _IFS_ whitespace characters is also treated
as a delimiter.

