= Bash completion

== Programmable Completion

When word completion is attempted for an argument to a command for which a
completion specification (a compspec) has been defined using the `complete`
builtin, the programmable completion facilities are invoked.

First, the command name is identified. If the command word is the empty string
(completion attempted at the beginning of an empty line), any compspec defined
with the `-E` option to `complete` is used. If a compspec has been defined for
that command, the compspec is used to generate the list of possible completions
for the word. If the command word is a full pathname, a compspec for the full
pathname, an attempt is made to find a compspec for the portion following the
final slash. If those searches do not result in a compspec, any compspec
defined with the `-D` option to `complete` is used as the default. If there is
no default compspec, bash attempts alias expansion on the command word as a
final resort, and attempts to find a compspec for the command word from any
successful expansion.

Once a compspec has been found, it is used to generate the list of matching
words. If a compspec is not found, the default bash completion as described
above under Completing is performed.

First, the actions specified by the compspec are used. Only mathes which are
prefixed by the word being completed are returned. When the `-f` or `-d` option
is used for filename or directory name completion, the shell variable
`FIGNOREB` is used to filter the matches.

Any completions specified by a pathname expansion pattern to the `-G` option
are generated next. The words generated by the pattern need not match the word
being completed. The `GLOBIGNORE` shell variable is not used to filter the
matches, but the `FIGNORE` variable is used.

Next, the string specified as the argument to the `-W` option is considered.
The string is first split using the characters in the `IFS` special variable as
delimiters. Shell quotiong is hornored. Each word is then expanded using brace
expansion, tilde expansion, parameter and variable expansion, command
substitution, and arithmetic expansion. The results are split using the Word
Spliting rules. The results of the expansion are prefix-matched against the
word being completed, and the matching words become the possible completions.

After these matches have been generated, any shell function or command
specified with the `-F` and `-C` options is invoked. When the command or
function is invoked, the `COMP_LINE`, `COMP_POINT`, `COMP_KEY`, and `COMP_TYPE`
variables are assigned values. If a shell function is being invoked, the
`COMP_WORDS` and `COMP_CWORD` variables are also set. When the function or
command is invoked, the first argument ($1) is the name of the command whose
arguments are being completed, the second argument ($2) is the word being
completed on the current command line. No filtering of the generated
completions against the word being completed is performed; the function or
command has complete freedom in generating the matches.

Any function specified with `-F` is invoked first. The function may use any of
the shell facilities, including the `compgen` builtin. to generate the matches.
It must put the possible completions in the `COMPREPLY` array variable, one per
array element.

Next, any command specified with the `-C` option is invoked in an environment
equivalent to command substitution. It should print a list of completions, one
per line, to the standard output. Backslash may be used to escape a newline, if
necessary.

After all of the possible completions are generated, any filter specified with
the `-X` option is applied to the list. The filter is a pattern as used for
pathname expansion; a `&` in the pattern is replaced with the text of the word
being completed. A literal `&` may be escaped with a backslash; the backslash
is removed berfore attempting a match. Any completion that matches the pattern
will be removed from the list. A leading `!` negates the pattern; in this case
any completion not matching the pattern will be removed. If the `nocasematch`
shell option is enabled, the match is performed without regard to the case of
alphabetic characters.

Finally, any prefix and suffix specified with the `-P` and `-S` options are
added to each member of the completion list, and the result is returned to the
readline completion code as the list of possible completions.

If the previously-applied actions do not generate any matches, and the
`-o dirname` option was supplied to `complete` when the compspec was defined,
directory name completion is attempted.

If the `-o plusdirs` option was supplied to `complete` when the compspec was
defined, directory name completion is attempted and any matches are added to
the results of the other actions.

By default , if a compspec is found, whatever it generates is returned to the
completion code as the full set of possible completions. The default bash
completions are not attempted, and the readline default of filename completion
is disbled. If the `-o bashdefault` option was supplied to `complete` when the
compspec was defined, the bash bash default completions are attempeted if the
compspec generates no matches. If the `-o default` option was supplied to
compspec when the compspec was defined, readline's default completion will be
performed if the compspec (and, if attempted, the default bash completions)
generate no matches.

When a compspec indicates that direcotry name completion is desired, the
programmable completion functions force readline to append a slash to completed
names which are symbolic links to directories, subject to the value of the
`mark-directories` readline variable, regardless of the setting of the
`mark-symlinked-direcotries` readline variable.

There is some support for dynamically modifying completions. This is most
useful when used in combination with a default completion specified with
`complete -D`. It's possible for shell functions execute as completion handlers
to indicate teh completion should be retried by returning an exit status of
124. If a shell function returns 124, and changes the compspec associated with
the command on which completion is being attempted (supplied as the first
argument when the function is executed), programmable completion restarts from
the beginning, with an attempt to find a new compspec for that command. This
allows a set of completions to be built dynameically as completion is
attempted, rather than being loaded all at once.

== compgen

----
    compgen [option] [word]
----

Generate possible completion matches for word according to the options, which
may be any option accepted by the `complete` builtin with the exception of `-p`
and `-r`, and write the matches to the standard output. When using the `-F` or
`-C` options, the various shell variables set by the programmable completion
facilities, while available, will not have useful values.

The matches will be generated in the same way as if the programmable completion
code had generated them directly from a completion specification with the same
flags. If word is specified, only those completions matching word will be
displayed.

The return value is true unless an invalid option is supplied, or no matches
were generated.

== complete

----
    complete [-abcdefgjksuv] [-o comp-option] [-DE] [-A action] [-G globpat]
        [-W wordlist] [-F function] [-C command] [-X filterpat] [-P prefix]
        [-S suffix] name [name ...]
----

----
    complete -pr [-DE] [name ...]
----

Specify how arguments to each name should be completed. If the `-p` option is
supplied, or if no options are supplied, existing completion specifications are
printed in a way that allows them to be reused as input. The `-r` option
removes a completion specification for each name, or, if no names are supplied,
all completion specifications. The `-D` option indicates that the remaining
options and actions should apply to the "default" command completion; that is,
completion attempted on a command for which no completion has previously been
defined. The `-E` option indicates that the remaining options and actions
should apply to "empty" command completion; that is, completion attempted on a
blank line.

Other options, if specified, have the following meanings. The arguments to the
`-G`, `-W`, and `-X` options (and, if necessary, the `-P` and `-S` options)
should be quoted to protect them from expansion before the complete builtin is
invoked.

`-o comp-option`: The comp-option controls several aspects of the compspec's
behavior beyond the simple generation of completions.

-   `bashdefault`: Perform the rest of the default bash completions if the
    compspec generates no matches.

-   `default`: Use readline's default filename completion if the compspec
    generates no matches.

-   `dirnames`: Perform directory name completion if the compspec generates no
    matches

-   `filenames`: Tell readline that the compspec generates filenames, so it can
    perform any filename-specific processing (like adding a slash to directory
    names, quoting special characters, or suppressing trailing spaces).
    Intended to be used with shell functions.

-   `noquote`: Tell readline not to quote the completed words if they are
    filenames (quoting filenames is the default).

-   `nosort`: Tell readline not to sort the list of possible completions
    alphabetically.

-   `nospace`: Tell readline not to append a space (the default) to words
    completed at the end of the line.

-   `plusdirs`: After any matches defined by the compspec are generated,
    directory name completion is attempted and any matches are added to the
    results of the other actions.

`-A action`: The action may be one of the following to generate a list of
possible completions:

-   `alias`: Alias names. May also be specified as `-a`.

-   `arrayvar`: Array variable names.

-   `binding`: Readline keybinding names.

-   `builtin`: Names of shell builtin commands. May also be specified as `-b`.

-   `command`: Command names. May also be specified as `-c`.

-   `directory`: Directory names. May also be specified as `-d`.

-   `disabled`: Name of disabled shell builtins.

-   `enabled`: Name of enabled shell builtins.

-   `export`: Name of exported shell variables. May also be specified as `-e`.

-   `file`: File name. May also be specified as `-f`.

-   `function`: Names of shell functios.

-   `group`: Group names. May also be specified as `-g`.

-   `helptopic`: Help topics as accepted by the `help` builtin.

-   `hostname`: Hostname, as taken from the file specified by the `HOSTFILE`
    shell variable.

-   `job`: Job names, if job control is active. May also be specified as `-j`.

-   `keyword`: SHell reserved words. May also be specified as `-k`.

-   `running`: Names of running jobs, if job control is active.

-   `service`: Service names. May also be specified as `-s`.

-   `setopt`: Valid arguments for the `-o` option to the `set` builtin.

-   `shopt`: Shell option names as accepted by the `shopt` builtin.

-   `signal`: Signal names.

-   `stopped`: Names of stopped jobs, if job control is active.

-   `user`: User names, May also be specified by `-u`.

-   `variable`: Names of all shell veriables. May also be specified as `-v`.

`-C command`: command is executed in subshell environment, and its output is
used as the possible completions.

`-F function`: The shell function function is executed in the current shell
environment. When the function is executed, the first argument ($1) is the name
of the command whose arguments are being completed, the second argument ($2) is
the word being completed, and the third argument ($3) is the word preceding the
word being completed on the current command line. When it finishes, the
possible completions are retrieved from teh value of the `COMPREPLY` array
variable.

`-G globpat`: The pathname expansion pattern globpat is expanded to generate
the possible completions.

`-P prefix`: prefix is added at the beginning of each possible completion after
all other options have been applied.

`-S suffix`: suffix is appended to each possible completion after all other
options have been applied.

`-W wordlist`: The wordlist is split using the characters in the IFS special
variable as delimiters, and each resultant word is expanded. The possible
completions are the members of the resultant list which match the word being
completed.

`-X filterpat`: filterpat is a pattern as used for pathname expansion. It is
applied to the list of possible completions generated by the preceding options
and arguments, and each completion matching filterpat is removed from the list.
A leading ! in filterpat negates the pattern; in this case, any completion not
matching filterpat is removed.

== compopt

----
    compopt [-o option] [-DE] [+o option] [name]
----

Modify completion options for each name according to the options, or for the
currently-executing completion if no names are supplied. If no options are
given, display the completion options for each name or the current completion.
The possible values of option are those valid for the `complete` builtin. The
`-D` option indicates that the remaining options should apply to the "default"
command completion; that is, completion attempted on a command for which no
completion has previously been defined. The `-E` option indicates that the
remaining options should apply to "empty" command completion; that is,
completion attempted on a blank line.

The return value is true unless an invalid option is supplied, an attempt is
made to modify the options for a name for which no completion specification
exists, or an output error occurs.

== Examples

Display all existing completion specification:

----
    complete
----

Or:

----
    complete -p
----

Remove a specific completion specification:

----
    complete -r {comp}
----

Remove all completion specification:

----
    complete -r
----

Define a completion specification for default:

----
    $ complete -D -W "1 2 3"
    $ <tab><tab>
    1  2  3
    $ cmd <tab><tab>
    1  2  3
----

Define a completion specification for empty command:

----
    $ complete -E -W "1 2 3"
    $ <tab><tab>
    1  2  3
    $ cmd <tab><tab>

----

Define a completion specification by using `-G` option:

----
    TODO: I don't know how to use this option. Please tell me if you know it.
----

Define a completion specification by using `-W` option:

----
    $ complete -W "1 2 3" cmd
    $ cmd <tab><tab>
    1  2  3
----

Define a completion specification by using `-F` option:

----
    $ func() { COMPREPLY=( $(compgen -W "11 22 33" -- $2) ); }
    $ complete -F func cmd
    $ cmd <tab><tab>
    11  22  33
----

Define a completion specification which will add a suffix on each completion:

----
    $ complete -W "1 2 3" -S "a" cmd
    $ cmd <tab><tab>
    1a  2a  3a
----

== References

-   `man bash`
