= mktemp

----
    mktemp [OPTION]... [TEMPLATE]
----

Create a temporary file or directory, safely, and print its name. TEMPLATE must
contain at least *3* consecutive `X' in last component. If TEMPLATE is not
specified, use _tmp.XXXXXXXXXX_, and --tmpdir is implied. Files are created
_u+rw_, and directories _u+rwx_, minus umask restrictions.

== Options

`-d, --directory`: create a directory, not a file.

`-u, --dry-run`: do not create anything; merely print a name (unsafe).

`-q, --quiet`: suppress diagnostics about file/dir-creation failure.

`--suffix=SUFF`: append SUFF to TEMPLATE; SUFF must not contain a slash. This
option is implied is TEMPLATE does not end in X.

`-p DIR, --tmpdir[=DIR]`: interpret TEMPLATE relative to DIR; if DIR is not
specified, use $TMPDIR is set, else /tmp. With this option, TEMPLATE *must not*
be absolute name; unlike with _-t_, TEMPLATE may contain slashed, but mktemp
creates only the final component.

`-t`: interpret TEMPLATE as a single file component (must not contain slash),
relative to a directory: $TMPDIR, if set; else the directory specified via
_-p_; else /tmp [decrecated].

== Examples

Create a temporary file without TEMPLATE:

----
    $ mktemp
    /tmp/tmp.Im8N8padlx
----

Create a temporary file with a relative path TEMPLATE:

----
    $ mktemp ../template.XXX
    ../template.tJt
----

Create a temporary file with an absolute path TEMPLATE:

----
    $ mktemp /tmp/template.XXX
    /tmp/template.EGh
----

Create a temporary file with TEMPLATE appending suffix:

----
    $ mktemp --suffix=123 template.XXX
    template.rvH.txt
----


Create a temporary file relative to a directory with a relative path TEMPLATE
(dry-run, for the directory _a_ in example doesn't exit):

----
    $ mktemp -u -p a/b/c d/template.XXX
    a/b/c/d/template.R4o
----

[NOTE]
DIR set by _-p_ option can be a relative path or an absolute path.

[NOTE]
When using _-p_ option, TEMPLATE must not be an absolute path.

Create a temporary file relative to a directory with TEMPLATE which is a single
file name component.

----
    $ mktemp -u -p a/b/c -t template.XXX

----

[NOTE]
When using _-t_ option, TEMPLATE must not contain slash.


